[package]
name = "mini-sansio-dns"
version = "1.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/iliabylich/mini-sansio-dns"
authors = ["Ilya Bylich <ibylich@gmail.com>"]
description = "Sans-IO implementation of DNS protocol"

[dev-dependencies]
anyhow = "1.0"
rustix = { version = "1", features = ["fs", "event", "net"] }
